apiVersion: apps/v1
kind: Deployment
metadata:
    name: static-html
spec:
    selector:
        matchLabels:
            run: static-html
    replicas: 2
    template:
        metadata:
            labels:
                run: static-html
        spec:
            containers:
            - name: static-html
              image: neospacian4/personalcv:1.0
              ports:
                - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
    name: statichtml-service-nodeport
spec:
    type: NodePort
    selector: 
        name: static-html-nodeport
    ports:
        - port: 8080
          targetPort: 8080
          nodePort: 30001


---

apiVersion: v1
kind: Service
metadata:
    name: statichtml-service-loadbalancer
spec:
    type: LoadBalancer
    selector: 
        name: static-html-loadbalancer
    ports:
        - port: 8080
          targetPort: 8080
    # LoadBalancerIP: x.x.x.x

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: statichtml-service-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
    - host: example.com
      http:
        paths:
        - path: /service-1
          backend:
            serviceName: service1
            servicePort: 4200
        - path: /service2
          backend:
            serviceName: service2
            servicePort: 8080
